# syntax=docker/dockerfile:1

FROM golang:1.24

WORKDIR /app

# copy all files from current directory to working directory
COPY . .

# download dependencies
RUN go mod download

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["go", "run", "."]