# syntax=docker/dockerfile:1

FROM golang:1.24

WORKDIR /app

# copy all files from current directory to working directory
COPY . .

# download dependencies
RUN go mod download

# build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /treespotter-backend

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["/treespotter-backend"]